name: salon_booking_app
description: تطبيق حجز صالونات التجميل.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  smooth_page_indicator: ^1.2.1  # for onboarding page indicator
  lottie: ^3.3.1  # for Lottie animations
  flutter_svg: ^2.0.17  # for SVG support

  # إدارة الحالة
  provider: ^6.1.4
  http: ^1.3.0
  shared_preferences: ^2.5.3
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.3.0
  # لواجهة المستخدم
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  intl: ^0.19.0

  # لتحديد الموقع
  geolocator: ^13.0.4
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  permission_handler: ^11.4.0

  # للواجهة
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/salons/
    - assets/images/products/
    - assets/images/staff/
    - assets/images/onboarding/
    - assets/images/yasser.jpg


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/Fonts/Cairo-Regular.ttf
        - asset: assets/Fonts/Cairo-Bold.ttf
          weight: 700
