name: salon_booking_app
description: تطبيق حجز صالونات التجميل.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # إدارة الحالة
  provider: ^6.1.1

  # لواجهة المستخدم
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  intl: ^0.19.0

  # لتحديد الموقع
  geolocator: ^13.0.3

  # للواجهة
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.12.0
  permission_handler: ^11.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/yasser.jpg


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/Fonts/Cairo-Regular.ttf
        - asset: assets/Fonts/Cairo-Bold.ttf
          weight: 700
